export const popularAirports = [
  // India - Top
  { iata: 'BOM', name: 'Chhatrapati Shivaji Maharaj International', city: 'Mumbai', country: 'India' },
  { iata: 'DEL', name: 'Indira Gandhi International', city: 'New Delhi', country: 'India' },
  { iata: 'BLR', name: 'Kempegowda International', city: 'Bangalore', country: 'India' },
  { iata: 'HYD', name: 'Rajiv Gandhi International', city: 'Hyderabad', country: 'India' },
  { iata: 'MAA', name: 'Chennai International', city: 'Chennai', country: 'India' },
  { iata: 'CCU', name: 'Netaji Subhash Chandra Bose', city: 'Kolkata', country: 'India' },
  { iata: 'AMD', name: 'Sardar Vallabhbhai Patel', city: 'Ahmedabad', country: 'India' },
  { iata: 'PNQ', name: 'Pune Airport', city: 'Pune', country: 'India' },
  { iata: 'GOI', name: 'Dabolim Airport', city: 'Goa', country: 'India' },
  { iata: 'GOX', name: 'Manohar International', city: 'North Goa', country: 'India' },
  { iata: 'LKO', name: 'Chaudhary Charan Singh International', city: 'Lucknow', country: 'India' },
  { iata: 'ATQ', name: 'Sri Guru Ram Dass Jee', city: 'Amritsar', country: 'India' },
  { iata: 'COK', name: 'Cochin International', city: 'Kochi', country: 'India' },
  { iata: 'TRV', name: 'Trivandrum International', city: 'Thiruvananthapuram', country: 'India' },
  { iata: 'IXC', name: 'Chandigarh International', city: 'Chandigarh', country: 'India' },
  { iata: 'JAI', name: 'Jaipur International', city: 'Jaipur', country: 'India' },
  { iata: 'PAT', name: 'Jay Prakash Narayan', city: 'Patna', country: 'India' },
  { iata: 'VNS', name: 'Lal Bahadur Shastri', city: 'Varanasi', country: 'India' },
  // International - Top
  { iata: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'UAE' },
  { iata: 'LHR', name: 'Heathrow', city: 'London', country: 'UK' },
  { iata: 'JFK', name: 'John F. Kennedy International', city: 'New York', country: 'USA' },
  { iata: 'EWR', name: 'Newark Liberty International', city: 'New York', country: 'USA' },
  { iata: 'SIN', name: 'Changi', city: 'Singapore', country: 'Singapore' },
  { iata: 'BKK', name: 'Suvarnabhumi', city: 'Bangkok', country: 'Thailand' },
  { iata: 'CDG', name: 'Charles de Gaulle', city: 'Paris', country: 'France' },
  { iata: 'SYD', name: 'Sydney Kingsford Smith', city: 'Sydney', country: 'Australia' },
  { iata: 'YYZ', name: 'Toronto Pearson', city: 'Toronto', country: 'Canada' },
  { iata: 'FRA', name: 'Frankfurt', city: 'Frankfurt', country: 'Germany' },
  { iata: 'MUC', name: 'Munich Airport', city: 'Munich', country: 'Germany' },
  { iata: 'NRT', name: 'Narita International', city: 'Tokyo', country: 'Japan' },
  { iata: 'HND', name: 'Haneda', city: 'Tokyo', country: 'Japan' },
  { iata: 'ICN', name: 'Incheon International', city: 'Seoul', country: 'South Korea' },
  { iata: 'HKG', name: 'Hong Kong International', city: 'Hong Kong', country: 'Hong Kong' },
  { iata: 'KUL', name: 'Kuala Lumpur International', city: 'Kuala Lumpur', country: 'Malaysia' },
  { iata: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey' },
  { iata: 'DOH', name: 'Hamad International', city: 'Doha', country: 'Qatar' },
  { iata: 'AUH', name: 'Zayed International', city: 'Abu Dhabi', country: 'UAE' },
  { iata: 'SFO', name: 'San Francisco International', city: 'San Francisco', country: 'USA' },
  { iata: 'LAX', name: 'Los Angeles International', city: 'Los Angeles', country: 'USA' },
  { iata: 'ORD', name: 'O\'Hare International', city: 'Chicago', country: 'USA' },
  { iata: 'AMS', name: 'Schiphol', city: 'Amsterdam', country: 'Netherlands' },
  { iata: 'MAD', name: 'Adolfo Suárez Madrid–Barajas', city: 'Madrid', country: 'Spain' },
  { iata: 'BCN', name: 'Barcelona–El Prat', city: 'Barcelona', country: 'Spain' },
  { iata: 'FCO', name: 'Leonardo da Vinci–Fiumicino', city: 'Rome', country: 'Italy' },
  { iata: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland' }
];

export const hotRoutes = ['BOM', 'DEL', 'BLR', 'DXB', 'LHR'];
